### ISSUE TITLE
Insecure feature: Download Windows Executable

### ISSUE THREAD

**Issue by bananabr** [greenbone/gsa#2360] opened 2020-08-04 17:11 UTC
Please refer to https://github.com/greenbone/openvas/issues/563. I didn't want to replicate it but this is probably the right repo to report it.

**Comment by bjoernricks** [comment] 2020-08-04 19:29
We are already looking into it and working on the issue

**Comment by cfi-gb** [comment] 2020-08-07 05:12
@bjoernricks @bananabr I have transferred https://github.com/greenbone/gvmd/issues/1228 to the correct repository (GVMD is responsible for the generation of the credential installer) and i guess this issue could be closed as a duplicate (or even deleted).

**Comment by bjoernricks** [comment] 2020-08-07 05:57
@cfi-gb i'll close it as duplicate of https://github.com/greenbone/gvmd/issues/1228

**Closed by bjoernricks** 2020-08-07 05:57 UTC
Labels: bug, duplicate
