### ISSUE TITLE
[20.8.1] Build with the bundled node modules fails

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/gsa#2717] opened 2021-02-11 09:55 UTC
It looks like some node modules are missing in the package, because the build fails with: 
```
 94%] Built target gsad
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Can't make a request in offline mode ("https://registry.yarnpkg.com/@babel/core/-/core-7.10.4.tgz")
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

```
The version in the bundled tar file is  7.12.10 but 7.10.4 is requested in package.json file

**Comment by tuxmaster5000** [comment] 2021-02-11 10:23
And the yarn.lock file also contains the pointer to version 7.10.4

**Comment by bjoernricks** [comment] 2021-02-11 12:47
The used version of @babel/core is 7.10.4 (see https://github.com/greenbone/gsa/blob/v20.8.1/gsa/yarn.lock#L74). This version is available at the npm registry (https://www.npmjs.com/package/@babel/core/v/7.10.4). Therefore this problem is not caused by an issue with our configuration.

> Can't make a request in offline mode

This sentence is very suspicious to me. Haven't seen that before and resolving a locally not available package without internet access (offline mode) is of course not possible. Could you please check your cmake settings if `YARN_OFFLINE` is set? And if yes please set that setting to OFF.

**Comment by tuxmaster5000** [comment] 2021-02-12 06:19
Yes YARN_OFFLINE is set. And build my own offline package based on the yarn.lock file of the gsa tar ball will work.
When you look in the tar ball for the modules from github:
node_modules/react-scripts/node_modules/@babel/core/package.json
it is market as 7.12.10

**Comment by bjoernricks** [comment] 2021-02-12 07:45
IMHO in that case our released gsa node modules files are broken. We are going to re-upload new files.

**Comment by swaterkamp** [comment] 2021-02-12 14:44
I uploaded new node_modules to the release. Could you try building again and let us know, if everything is ok?

**Comment by tuxmaster5000** [comment] 2021-02-15 11:06
Yes the new tar ball will work.
Thanks.

**Closed** 2021-02-15 11:11 UTC
Labels: bug
