### ISSUE TITLE
Error in make for gsa-7.0.3

### ISSUE THREAD

**Issue by Chartman123** [greenbone/gsa#510] opened 2018-04-06 09:14 UTC
When I try to build the gsa-7.0.3, I get the following error:

Scanning dependencies of target gettext-json
[ 80%] Generating gsad-zh_CN.json
[ 82%] Generating gsad-ar.json
[ 85%] Generating gsad-de.json
[ 88%] Generating gsad-fr.json
Traceback (most recent call last):
  File "/home/openvas/src/gsa-7.0.3/tools/po2json", line 66, in <module>
    main()
  File "/home/openvas/src/gsa-7.0.3/tools/po2json", line 62, in main
    convert(sys.argv[1], sys.argv[2])
  File "/home/openvas/src/gsa-7.0.3/tools/po2json", line 45, in convert
    po_f = polib.pofile(in_name)
  File "/usr/lib/python2.7/dist-packages/polib.py", line 138, in pofile
    return _pofile_or_mofile(pofile, 'pofile', **kwargs)
  File "/usr/lib/python2.7/dist-packages/polib.py", line 86, in _pofile_or_mofile
    instance = parser.parse()
  File "/usr/lib/python2.7/dist-packages/polib.py", line 1320, in parse
    self.process(keywords[tokens[0]])
  File "/usr/lib/python2.7/dist-packages/polib.py", line 1464, in process
    self.current_line)
IOError: Syntax error in po file (line 430)
src/po/CMakeFiles/gettext-json.dir/build.make:74: recipe for target 'src/po/gsad-fr.json' failed
make[2]: *** [src/po/gsad-fr.json] Error 1
CMakeFiles/Makefile2:1020: recipe for target 'src/po/CMakeFiles/gettext-json.dir/all' failed
make[1]: *** [src/po/CMakeFiles/gettext-json.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cfi-gb** [comment] 2018-04-06 09:32
@Chartman123 Duplicate of #498 and #464 and already fixed with #493

Please use the repository search on top before reporting any issues. Thanks.

**Comment by Chartman123** [comment] 2018-04-06 09:34
Yeah I found the closed reports after that... So I have to wait for a new release or fix it in the source files for myself?

**Closed** 2018-04-06 09:36 UTC
