### ISSUE TITLE
Failed to bind port 80 on docker-compose setup

### ISSUE THREAD

**Issue by cyber01** [greenbone/gsa#3957] opened 2024-01-29 16:27 UTC
### Expected behavior

It will listen on port 80 inside the container and port 9392 outside the container.

### Actual behavior

When you try to listen on port 80 inside a container, an error appears in the logs. As a result, after starting the container, it will not be accessible via 127.0.0.1:9392 because refers to port 80, which is not accessible inside the container

### Steps to reproduce

Just follow the instructions at https://greenbone.github.io/docs/latest/22.4/container/index.html and the error will appear similar to what I describe. Occurs when using docker-compose.yml without any modifications

### GVM versions

All stable images in docker (like original docker-compose.yml)

### Environment

**Operating system:**

**Installation method / source:** (packages, source installation)

Docker containers (docker-compose.yml)

### Logfiles
![2024-01-29_19-25-33](https://github.com/greenbone/gsa/assets/1358988/7f0ca0ab-88ab-457a-b326-11bda05b65fb)

```
```

**Comment by bjoernricks** [comment] 2024-01-30 08:52
Hi,

I am sorry but I can't reproduce your issue. I've changed my config of the gsa service to:

```yml
  gsa:
    image: greenbone/gsa:stable
    restart: on-failure
    ports:
      - 127.0.0.1:80:9392
    volumes:
      - gvmd_socket_vol:/run/gvmd
    depends_on:
      - gvmd
    environment:
      GSAD_ARGS: "-f -p 80 --http-only"
```

an I am able to access GSA via my browser on port 9392. Maybe your compose file is different?

**Comment by cyber01** [comment] 2024-01-30 08:57
Hello, original docker-compose.yml is differs than you show:
![image](https://github.com/greenbone/gsa/assets/1358988/d75e5860-ffd1-4440-894e-9bf13c1eb72b)

9392 - external port, 80 - internal port.
But i got error on first screenshot.

**Comment by bjoernricks** [comment] 2024-01-30 09:10
Sorry I mixed up the host port and container port. But nevertheless I am still not able to reproduce your issue. I suppose your docker setup is different and therefore your container is not allowed to bind on ports < 1024.

You can fix it by just changing
```yml
    ports:
      - 127.0.0.1:9392:80
```
to
```yml
    ports:
      - 127.0.0.1:9392:9392
```

**Comment by cyber01** [comment] 2024-01-30 09:29
Hmm, im tryed on another host (with newer docker engine) and error is gone.
I got error on Docker Engine 20.10.15, but on Docker Engine 25.0.1 error is gone

**Comment by bjoernricks** [comment] 2024-01-30 09:34
Good to know. That's what I expected, some issue with docker itself. Thanks for letting me know. I am closing this issue.

**Closed by bjoernricks** 2024-01-30 09:34 UTC
Labels: bug, feedback required
