### ISSUE TITLE
gsa-ng: A click on the "close" button of a protected scan config makes the box jump below

### ISSUE THREAD

**Issue by cfi-gb** [greenbone/gsa#1027] opened 2018-10-18 09:06 UTC
### Expected behavior

Pop-up box should be closed after clicking the X/close icon.

### Actual behavior

Pop-up box is moving some lines below after clicking the X/close icon.

### Steps to reproduce

1. Open https://example.com:9392/scanconfigs
2. Click on the "Tool" icon of e.g. "System Discovery"
3. Click on the "X" icon in the new pop-up box (see screenshot)

### GVM versions

GSA Version: master build from a git checkout 10 minutes ago
Browser: Firefox 62.0.3

![screenshot_2018-10-18_11-03-32](https://user-images.githubusercontent.com/34644702/47143606-d7759e00-d2c5-11e8-8849-29ab968f0ff1.png)

**Comment by bjoernricks** [comment] 2018-10-18 11:13
I can't reproduce the behavior. For me the dialog is closed after clicking on the X button at the dialog title. @cfi-gb do you get some error/traceback in the browser console?

**Comment by swaterkamp** [comment] 2018-10-18 11:14
Same here, the dialog closes as expected.

**Comment by cfi-gb** [comment] 2018-10-18 12:01
It might have something to do with the mouse sensitivity on a double click. If i keep the mouse button pressed for a few seconds and releasing it afterwards the box jumps around as well but closes afterwards.

No errors/tracebacks or similar in the browser console.

**Comment by swaterkamp** [comment] 2018-12-10 08:02
Closing this because:
* jumping dialogs are fixed (at least when closing in a scrolled window (#1082)
* protected scan configs can't be edited at all anymore (button is disabled since a while, as it seems)

**Closed by swaterkamp** 2018-12-10 08:02 UTC
