### ISSUE TITLE
[Arch Linux] Error Message in web-gui "Failed to start task: Service temporarily down"

### ISSUE THREAD

**Issue by Davetheraveuk** [greenbone/gsa#1868] opened 2019-12-17 11:22 UTC
Hi,
I have tried to get this openvas software running on my system.
I have followed both official guides and non-official guides.
I do not know what else to do.
I have tried for several days to figure out the problem.

My system is **Arch Linux** with an **AMD cpu**.

![Screenshot from 2019-12-17 11-19-08](https://user-images.githubusercontent.com/11774054/70991317-1f0cdb00-20bf-11ea-9e82-78a8642c2b5c.png)

Thanks.
Dave.

**Comment by cfi-gb** [comment] 2019-12-17 13:06
Unfortunately this is not a bug in GVM (especially not within the GSA) and more a setup issue with the GVM components (GSA can't reach manager daemon or similar).

Please follow the instructions here on how to get support for such issues:

```
1. Be aware that this is not a support forum. If your issue is rather a question
   than a bug report, please use our community forum at
   https://community.greenbone.net/c/gse instead.
```

**Comment by bjoernricks** [comment] 2019-12-17 13:06
First of all it is better to provide all the info requested in the issue template. Especially the used software component versions.

In your case either gsad, gvmd or the scanner daemon isn't responding.

**Comment by Davetheraveuk** [comment] 2019-12-17 13:34
Okay, I got a solution:
`sudo openvassd`

@cfi-gb @bjoernricks Thanks for pointing me in the right direction:
`((https://github.com/greenbone/openvas/blob/a2dc191d3b9ef27a4d057b82f115dcf284b28e1c/INSTALL#L115))
`

**Comment by swaterkamp** [comment] 2020-02-17 15:58
Closing as this seems solved.

**Closed by swaterkamp** 2020-02-17 15:58 UTC
