### ISSUE TITLE
Broken "Hosts by Modification Time" Graph

### ISSUE THREAD

**Issue by shibumi** [greenbone/gsa#567] opened 2018-04-24 10:34 UTC
### Expected behavior
I should be able to edit the Openvas Dashboard and see the "Hosts by Modification Time"-Graph

### Current behavior

The "Hosts by Modification Time"-Graph is loading forever and breaks the option to edit the dashboard.

### Steps to reproduce
It happened after a restore of openvas from a backup. (whole VM snapshot backup)

### GVM versions
**gsa:** 7.0.2

**gvm:** 7.0.2

**openvas-scanner:** 5.1.1

**gvm-libs:** no idea

**openvas-smb:** no idea

### Environment
**Operating system:** CentOS7 with Atomicorps Sources

**Installation method / source:** (packages, source installation)

Packages via Atomicorp Openvas RPMs

### Logfiles

No idea which logs you want.. 

### Screencast

Here is a Screencast of the issue. You might need Chromium/Chrome to play the video: https://paste.xinu.at/WIHv/

**Comment by bjoernricks** [comment] 2018-04-24 10:45
@timopollmeier do you have some time to look at this issue? Should be broken in GOS too.

**Comment by bjoernricks** [comment] 2018-04-24 10:46
Btw. the screencast doesn't work for me on linux with firefox.

**Comment by timopollmeier** [comment] 2018-05-22 15:49
Sorry for answering so late.
If the chart looks like it keeps loading forever, chances are that the problem is in the JavaScript.
Are there any error message in the console that's part of developer tools in the browser?
Or is there a HTTP request starting with something like this in the network tab of the developer tools that never finishes: https://127.0.0.1:9392/omp?cmd=get_aggregate&xml=1&filter=... ?

**Comment by shibumi** [comment] 2018-05-22 18:47
@timopollmeier no problem. Thanks for coming back to this issue :)
I will check this when I am at work tomorrow.

**Comment by shibumi** [comment] 2018-05-23 07:28
@timopollmeier Are you talking about error messages like this one?
```
gsa_line_chart.js:1112 Uncaught TypeError: Cannot read property 'stat' of undefined
    at LineChartGenerator.timeLine (gsa_line_chart.js:1112)
    at LineChartGenerator.BaseChartGenerator.transformData (gsa_graphics_base.js:125)
    at LineChartGenerator.BaseChartGenerator.generateData (gsa_graphics_base.js:155)
    at ChartController.dataLoaded (gsa_dashboard.js:2592)
    at DataSource.dataLoaded (gsa_dashboard.js:2970)
    at gsa_dashboard.js:2937
    at Object.<anonymous> (d3.v3.js:1991)
    at Object.event (d3.v3.js:504)
    at XMLHttpRequest.respond (d3.v3.js:1944)
```

I have also a full JS log of stuff like this:
```
Error: <rect> attribute width: A negative value is not valid. ("-0.0014508127548789468")
```

**Comment by timopollmeier** [comment] 2018-07-16 13:30
Unfortunately we haven't been able to reproduce the problem yet.
Can you filter the hosts in a way that makes the chart work again, e.g. by using a filter that returns no hosts at all?
If you can make the chart work with the filter, can you find any filter criteria that select only a few hosts but still break the chart?

**Comment by bjoernricks** [comment] 2019-10-22 07:54
OpenVAS/GVM 9 is end of life now. Therefore I am closing this issue.

**Closed by bjoernricks** 2019-10-22 07:54 UTC
Labels: bug
