### ISSUE TITLE
[9.0.0] Sensible sorting of TLS-Certificates expiry

### ISSUE THREAD

**Issue by tgurr** [greenbone/gsa#1923] opened 2020-01-15 15:06 UTC
# Expected behavior

Sensible sorting of expiration dates.

### Steps to reproduce

Go to Assets - TLS-Certificates and try to sort them via expiration date and get something like this:

![greenbone_certificates_sort](https://user-images.githubusercontent.com/414984/72444647-b3e32100-37b0-11ea-8f57-be5629f6a8bc.png)

### GVM versions

**gsa:** 9.0.0

**gvm:** 9.0.0

**openvas-scanner:** 7.0.0

**gvm-libs:** 11.0.0

### Environment

**Operating system:** Linux

**Comment by swaterkamp** [comment] 2020-01-21 08:59
Hi @tgurr ,
thanks for reporting this issue.
I tried reproducing it in GSA-9.0 and master, but on my machine the sorting works just fine. I even switched languages and timezones to match your data, but everything works just fine for me.
Could you try and rebuild GSA and test again? Maybe that already helps.

**Comment by tgurr** [comment] 2020-01-21 13:49
I'm afraid rebuilding GSA doesn't seem to do the trick for me, but I've some further info, it actually does a sorting when clicking on sorting by `Expires` but the sorting is done by `Last seen` instead and the little sorting indicator arrow changes for both no matter if trying to sort via `Expires` or `Last seen`. Also when trying to sort via `Activates` it only changes the view once after that after trying to change ascending/descending doesn't have any effect.

![gsa_sorting](https://user-images.githubusercontent.com/414984/72810066-28103f80-3c5d-11ea-9ac8-cbbf6c69ffaf.gif)

I also tried switching the `User Interface Language` to English but it doesn't change anything for me either. 

Same experience in both the latest Chromium and Firefox.

**Comment by root360-AndreasUlm** [comment] 2020-03-26 03:19
Hi,

I can confirm this behaviour with my installation of GSA-9.0 build from sources, too.

1. Page loaded with default sorting: ![image](https://user-images.githubusercontent.com/17042256/77604835-b9c55300-6f13-11ea-9728-67adfea9f7f9.png)
1. table sorted by clicking on 'Expires' (both 'Expires' and 'Last seen' are marked as sorted) ![image](https://user-images.githubusercontent.com/17042256/77604812-ac0fcd80-6f13-11ea-9fac-ff47c23ca31e.png)

When analyzing the properties you can see that wrong sorting keys are specified:
* props of 'Activities' ![image](https://user-images.githubusercontent.com/17042256/77606678-728d9100-6f18-11ea-97f1-56e2b3b86dab.png)
* props of 'Expires' ![image](https://user-images.githubusercontent.com/17042256/77606687-833e0700-6f18-11ea-9543-545acb294392.png)
* props of 'Last seen' ![image](https://user-images.githubusercontent.com/17042256/77606711-95b84080-6f18-11ea-9671-be2e328cf70c.png)

That shows and can be backed by the following screenshot that even sorting by 'Activities' does not sort by Activities but by a key named 'hosts':
![image](https://user-images.githubusercontent.com/17042256/77606783-cdbf8380-6f18-11ea-91fe-5aa074cbd413.png)

Unfortunately I'm not a react developer thus can not further debug the code to find the cause but maybe those information help you already.


Regards,
Andreas

**Comment by swaterkamp** [comment] 2020-03-26 09:56
Thank you for the detailed report, @root360-AndreasUlm .
I still can't get it to fail and a co-worker was also unable to reproduce.
![activatesprops](https://user-images.githubusercontent.com/32056637/77633233-7557a880-6f4f-11ea-8c61-733dd17b8a24.png)
I would guess that the problem was fixed in some GSA-9.X version past 9.0.0 (though I can't find a fitting commit with a quick search) and that maybe you and @tgurr are still on that version?
Maybe I was a bit vague about what I meant with rebuilding GSA. I was, for some reason, expecting you would get the latest version and rebuild with that, instead of just keeping 9.0.0 for the rebuild. Sorry for that. Does getting a newer version of GSA fix the problem for you?

**Comment by tgurr** [comment] 2020-03-26 12:06
@swaterkamp I'm also on GSA 9.0.0 since it's the latest available release version and the only version we package. I didn't test any later version or git master/snapshot since I feared there might be incompatible changes in combination with using release version for the other greenbone security suite parts.

**Comment by swaterkamp** [comment] 2020-03-26 13:26
You should be able to combine any 9.x versions of gvmd and gsa. I would not package master, though, as that is our development branch that might break or show unexpected behaviour.

**Comment by swaterkamp** [comment] 2020-03-26 14:03
I found the commit that is responsible for me not being able to reproduce, because it's fixed already: https://github.com/greenbone/gsa/pull/1830/commits/1ba16131d7321ddd16efcf4dad771965b20c475a
It was merged into GSA-9.0 on Dec 3, 2019, about two months after the 9.0.0 release.

**Comment by tgurr** [comment] 2020-03-26 14:48
@swaterkamp Thank you very much, that seems to do the trick for me as well.

I've added the patch to our distribution package: https://git.exherbo.org/net.git/commit/?id=e9064b0951ffa0dffcb13a71e598ef6a4ede6e79

It would be nice to have point releases of the various components more often for this kind of things.

**Comment by bjoernricks** [comment] 2020-03-26 17:40
@tgurr currently we don't have the infrastructure for creating releases easily. It cost a lot of manual developer work at the moment. And because not many distribution are packaging a up to date version there was no effort from our side to do point releases. Therefore it is best to use the release branches instead of a released version.

**Comment by root360-AndreasUlm** [comment] 2020-04-01 04:29
I can confirm too that installing latest branch gsa-9.0 fixes this sorting issue.

**Closed** 2020-04-01 05:53 UTC
Labels: bug
